id: IE2D8ECE4
default_language: en
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:46:46.170808
last_modified: 2023-02-09 14:46:46.170895
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: en
bases:
  BBAC:
    base_file: BBAC.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
